### ISSUE TITLE
Conditional block wrappers

### ISSUE THREAD

**Issue by subchild** [pugjs/pug#2379] opened 2016-05-13 18:00 UTC
We're using something like this in Jade (not latest) but Pug doesn't appear to like calls to the same `block` in a single layout. 

Any known workarounds? Thanks.

```
if (!req.headers["x-pjax"])
    doctype html
    html(lang='en-us')
        head
        body
            main
                block content

if (req.headers["x-pjax"])
    main
		block content
```

The above code doesn't display the `content` block in either case.

**Comment by ForbesLindesay** [comment] 2016-05-14 11:06
Duplicate of #2367

**Closed by ForbesLindesay** 2016-05-14 11:06 UTC
