### ISSUE TITLE
Cannot bundle in webpack due to uglify-js dependency

### ISSUE THREAD

**Issue by euberdeveloper** [pugjs/pug#3110] opened 2019-02-11 19:57 UTC
When I bundle my server with webpack, I got this error:

```
Cannot find module '../lib/utils.js'
    at Function.webpackEmptyContext [as resolve] (

```

The cause is that you include uglify-js on your dependency, and webpack does not support it as a non-dev dependency.

![dependencies](https://user-images.githubusercontent.com/33126163/52589526-54152500-2e3f-11e9-9b0f-0d251db1b9d7.PNG)

With that dependency, bundling all with webpack and avoid to have the node_modules folder in the release server is not possible

**Comment by ForbesLindesay** [comment] 2019-02-12 14:44
Duplicate of #2889

**Closed by ForbesLindesay** 2019-02-12 14:44 UTC
