### ISSUE TITLE
Docs iteration examples - all renders say 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by gushogg-blake** [pugjs/pug#2756] opened 2017-03-10 13:50 UTC
I see this error message in all the examples here: https://pugjs.org/language/iteration.html

**Comment by pascaloliv** [comment] 2017-03-18 16:18
I think it's a duplicate of https://github.com/pugjs/pug/issues/2754.

**Closed** 2017-03-19 23:07 UTC
