### ISSUE TITLE
Use the name of a template file within this template file

### ISSUE THREAD

**Issue by djcaesar9114** [pugjs/pug#3026] opened 2018-06-21 07:13 UTC
Hello,
Not an issue but a question: I'd like to use the name of a template file (for example "test.pug") inside this template file, is there a way to do this?
Thanks :)

**Comment by ForbesLindesay** [comment] 2018-06-29 16:34
This is partially a duplicate of #3012. The answer is: not currently. We do want to implement the "import" functionality, but adding a way of retrieving the name of the current template is not currently anywhere on our roadmap.

**Closed by ForbesLindesay** 2018-06-29 16:34 UTC
