### ISSUE TITLE
How to use pug in deno?

### ISSUE THREAD

**Issue by Ojvar** [pugjs/pug#3276] opened 2020-07-11 07:51 UTC
Hi guys
I google a lot but I couldn't find any answer to my question
How can I use pug in Deno?
If I can't now, when it will ready for Deno?

Thanks

**Comment by ForbesLindesay** [comment] 2020-07-12 03:24
Duplicate of #3255

**Closed by ForbesLindesay** 2020-07-12 03:24 UTC

**Comment by Ojvar** [comment] 2020-10-21 08:25
I look forward to the release of the DENO version of this library  ;)
