### ISSUE TITLE
Feature request: parent class name reference

### ISSUE THREAD

**Issue by rahbari** [pugjs/pug#2437] opened 2016-06-29 16:25 UTC
It would be really nice if there is a parent class name reference.

so something like this:

```
.plan
  .plan-column
     .plan-column-item
     .plan-column-item
     .plan-column-item
  .plan-column
     .plan-column-item
     .plan-column-item
     .plan-column-item

```
can be written like this:

```
.plan
  &-column
    &-item
    &-item
    &-item
  &-column
    &-item
    &-item
    &-item
```

**Comment by ForbesLindesay** [comment] 2016-07-01 09:53
Duplicate of #2291

**Closed by ForbesLindesay** 2016-07-01 09:53 UTC
Labels: plugin-request
