### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by Penagwin** [pugjs/pug#2462] opened 2016-07-22 22:07 UTC
I have a index.jade file which contains the normal jade code, running ` pug -w *.jade ` renders it ok, creating a index.html as a result, but it also creates a index.js which is new to me and super annoying, is there any way to not create this file?

**Comment by TimothyGu** [comment] 2016-07-25 01:33
Huh, I can't reproduce this issue.

What is your pug-cli version?

**Comment by Penagwin** [comment] 2016-07-25 15:39
Unfortunately I am unable to reproduce it too? I know I spent a little while trying to solve it though. I'm on , I tried it with both the jade and pug-cli from npm; same result. 

Windows 10 using babun (cygwin)
Node v6.2.2
NPM v3.9.5
pug version: 2.0.0-beta4
pug-cli version: 1.0.0-alpha6


The file looks like this:
http://hastebin.com/uxifanuyiy.js

<br>
Hopefully somebody else might run into this eventually. I have no clue why it isn't doing it today. Thanks for your time though.

**Comment by TimothyGu** [comment] 2016-07-31 20:44
I'll close this for now. If anybody has more issues, file a new ticket or comment here.

**Closed by TimothyGu** 2016-07-31 20:44 UTC
Labels: Command Line

**Comment by Penagwin** [comment] 2016-08-08 16:27
I just ran into the same issue again yesterday....

![jqmwg6b](https://cloud.githubusercontent.com/assets/1349689/17487504/1842d2b6-5d63-11e6-8092-47b7b73cadf7.png)

index.jade
```
html
	body
		div Pengiuins
```

index.js
```
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(i){pug_rethrow(n,null,r)}var a=3,o=t.split("\n"),h=Math.max(r-a,0),s=Math.min(o.length,r+a),a=o.slice(h,s).map(function(n,e){var t=e+h+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+a+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"index.jade":"html\r\n\tbody\r\n\t\tdiv Pengiuins"};
;pug_debug_line = 1;pug_debug_filename = "index.jade";
pug_html = pug_html + "\u003Chtml\u003E";
;pug_debug_line = 2;pug_debug_filename = "index.jade";
pug_html = pug_html + "\u003Cbody\u003E";
;pug_debug_line = 3;pug_debug_filename = "index.jade";
pug_html = pug_html + "\u003Cdiv\u003E";
;pug_debug_line = 3;pug_debug_filename = "index.jade";
pug_html = pug_html + "Pengiuins\u003C\u002Fdiv\u003E\u003C\u002Fbody\u003E\u003C\u002Fhtml\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}
```

**Comment by TimothyGu** [comment] 2016-08-08 16:40
What's your pug-cli version?

**Comment by Penagwin** [comment] 2016-08-08 16:42
It's because of `-c` meaning compile for client, not just compile which I assumed based off all of the other compilers such as coffeescript... I'm sorry about that.
