### ISSUE TITLE
Using node modules in Pug

### ISSUE THREAD

**Issue by msantagata** [pugjs/pug#2615] opened 2016-11-13 12:01 UTC
Hi there,
I'm learning Pug while using it to produce HTML for email templates, and I'm very satisfied with my results so far.
I'm trying to write a simple mixin that puts the image width in the corresponding <img> property. Something like

`+print_image("image_file.jpg")`

that could render as

`<img src="image_file.jpg" width="350" height="auto"/>`

I know that getting image dimensions is out of pug's scope; I would like to be able to use something  [like this](https://github.com/image-size/image-size) to get the job done.
I tried installing it and including it, but This is my try:

```javascript
mixin print_image(file)
   -
      var sizeOf = require('image-size');
      var dimensions = sizeOf(file);
      var w=dimensions.width

   image(
      src=file
      height= w+"px"
   )
```

I'm compiling pug files through CodeKit, and I get a "require is not a function" error.
Thanks in advance for your help!

**Comment by adammockor** [comment] 2016-11-13 16:52
I don't know how it works inside CodeKit, but you can pass require via `options.globals` (https://pugjs.org/api/reference.html).

**Comment by msantagata** [comment] 2016-11-13 18:14
Thanks @adammockor!
I have tried to use gulp instead of CodeKit, and my gulpfile has this task for pug:

```javascript
gulp.task('pug', function(){
	return gulp.src('index.pug')
		.pipe(pug({
			pretty : true,
			globals : ['require']
		}))
		.pipe(gulp.dest("./"))
});
```

but I must do something wrong, since I always get "require is not a function" from the compiler.
Any hint?
Thanks!

**Comment by TimothyGu** [comment] 2016-11-13 19:14
Duplicate of #2604. Long story short: `require` is not a global function, and therefore isn't available in `new Function`.

**Closed by TimothyGu** 2016-11-13 19:14 UTC

**Comment by msantagata** [comment] 2016-11-13 19:17
thanks @TimothyGu, sorry for the duplication (god knows I've searched :) )

**Comment by msantagata** [comment] 2016-11-13 22:08
In case anybody has the same problem, what @jeromew proposed in #2604 worked like a charm for me:

gulp task:
```javascript
gulp.task('pug', function(){
	return gulp.src('index.pug')
		.pipe(pug({
			pretty : true,
      locals : {resize_img : require("image-size")}
		}))
		.pipe(gulp.dest('./'))
		.pipe(browserSync.reload({
			stream: true
		}))
});
```

mixin definition:
```javascript
mixin image(file)
	-
		var dimensions = resize_img(file);
		var w=dimensions.width

	image(src=file,width= w,height="auto")/
});
```

mixin call:
```javascript
+image("img/marker.png")
```

result:
```html
<image src="img/marker.png" width="72" height="auto"/>
```

**Comment by jeromew** [comment] 2016-11-14 08:57
Thanks for the @ mention so I can give a precision.
you have to understand the difference between compile time & render time in pug.

the solution you mention with `resize_img : require("image-size")` works because at render time, you give the `image-size` module a path to an image that can be found on the fs.

This is not usually what you want to do since accessing the filesystem at render time can slow down your application. In the case of a static image, it would be better if your template could be compiled with the image sizes so that every rendering does not need to access the image file.

I haven't done it myself, but I suppose that is what a filter could do or it could be a good candidate for a pug plugin. cf https://pugjs.org/language/filters.html for starting points.

using the `myFunc : require("module")` solution that I mentioned I usually best suited for modules that do not have a heavy blocking impact like `image-size` in the way you use it here (it uses 'openSync`, `readSync`, ... when used in synchronous mode)
