### ISSUE TITLE
The page of "http://www.pug-lang.com" is not accessible

### ISSUE THREAD

**Issue by gzhjs** [pugjs/pug#2327] opened 2016-04-20 01:49 UTC
"http://www.pug-lang.com","http://www.pug-lang.com/api/"…are not accessible.

**Comment by gzhjs** [comment] 2016-04-20 02:05
thank godness, "http://jade-lang.com" is still accessible

**Comment by TimothyGu** [comment] 2016-04-21 23:34
Duplicate of #2276.

**Closed by TimothyGu** 2016-04-21 23:34 UTC
