### ISSUE TITLE
Upgrading Jade to Pug -- "Syntax Error" ... Unable to ascertain where the problem is!

### ISSUE THREAD

**Issue by markcollinscope** [pugjs/pug#2540] opened 2016-09-14 11:44 UTC
Hello,

I've just upgraded to Pug from using Jade.

I'm getting error below at runtime - I have no issue with updating my .jade files, however I'm not too keen on a trial and error exercise to find out what the error is. Any assistance would be appreciated, otherwise it's back to Jade - unfortunately...

(so perhaps this could be a request for a more meaningful error message, as well -- many thanks for your assistance)...

**\* Error ***
SyntaxError: Unexpected token (4102:0)
    at Parser.pp$4.raise (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$1.parseVar (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:1034:28)
    at Parser.pp$1.parseVarStatement (/home/mark/SVN/DA/node_modules/pug/node_modules/pug-code-gen/node_modules/with/node_modules/acorn/dist/acorn.js:917:10)

**Comment by ForbesLindesay** [comment] 2016-09-14 13:20
What version of pug are you using?

This kind of error happens in two cases:

 1. When there's a bug in pug.  This was a pretty common problem in the early days of jade.  Thankfully it's now fairly rare.  This could be what you're suffering from and if it is we'd greatly appreciate your help in tracking it down.
 2. You have a statement that is not valid JavaScript.  i.e. the pug code would look something like:

```pug
- This is not JavaScript
```

Based on the stack trace.  I think this will be a variable declaration. (because `parseVarStatement` appears in the stack).  Therefore, I would try looking through your code for `var` declarations and check that all of them are syntactically valid.

If this turns out to be a bug in pug, we'd really appreciate a sample that reproduces the problem.  If you could post it either here, if it's small, or in a gist, if you're unable to narrow it down, that would be perfect.

**Comment by markcollinscope** [comment] 2016-09-14 14:20
@ForbesLindesay -- thanks for the assistance. I'll get back to you when I know if it is a bug in Pug or not.

**Comment by markcollinscope** [comment] 2016-09-14 14:20
@ForbesLindesay   -  "pug": "^2.0.0-beta6", - Thx.

**Comment by markcollinscope** [comment] 2016-09-15 12:11
@ForbesLindesay - I will get back to you however have slightly bigger issues at present...

**Comment by reubano** [comment] 2016-09-19 15:27
I'm getting a similar error. How do you get pug to tell the file and line number causing the error?

**Comment by reubano** [comment] 2016-09-19 16:06
So the offending line was `category = [metadata: {singular: 'tag', plural: 'tags'}]`. Weird thing is that `pug-lint` didn't report any errors.

**Comment by dxcqcv** [comment] 2016-11-29 03:15
I also got a similar error with update to pug2.0beta, and I do not know what means about error details, like

```

[10:50:24] Using gulpfile ~/dev/github/resume/gulpfile.js
[10:50:24] Starting 'html'...
[10:50:24] 'html' errored after 298 ms
[10:50:24] SyntaxError in plugin 'gulp-pug'
Message:
    Unexpected token (444:0)
Details:
    pos: 33992
    loc: [object Object]
    raisedAt: 33996
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by ForbesLindesay** [comment] 2017-01-18 14:16
I'm closing this as none of these provide enough information to reproduce the error.  If someone can provide example code that produces this error, please open a new issue and someone will investigate.

**Closed by ForbesLindesay** 2017-01-18 14:16 UTC
