### ISSUE TITLE
Setting object as an attribute value

### ISSUE THREAD

**Issue by dimitarkolev** [pugjs/pug#2385] opened 2016-05-16 12:13 UTC
If you set an attribute to an object that predefines toString() Inside the attribute you get object dump instead of the result from the toString() function.

**Comment by dimitarkolev** [comment] 2016-05-16 12:26
Needs some investigation on my side....

**Comment by dimitarkolev** [comment] 2016-05-16 12:32
It seems that instead of calling toString, Pug is converting the object to json string.

**Comment by ForbesLindesay** [comment] 2016-05-16 13:10
Duplicate of #2369.  You'll need to provide a `toJSON` that returns the same string as `toString` and then wait for the next update to pug.

**Closed by ForbesLindesay** 2016-05-16 13:10 UTC
