### ISSUE TITLE
How to compile pug on browser environment?

### ISSUE THREAD

**Issue by hmouhtar** [pugjs/pug#3113] opened 2019-02-13 12:29 UTC
Hi. I'm trying to compile pug on the fly with `pug.render()` function. However, I can't do it since one of the pug dependencies is file-system(fs) and the browser does not have access to that module, so I'm getting the following error in the console: 

`Uncaught Error: Cannot find module 'fs'
    at webpackMissingModule (index.js:3)`.

What could be the approach to either ignore this error or find a way to import pug that doesn't depend on the file-system module?

Thanks!

**Comment by PythonLinks** [comment] 2019-02-13 13:37
Here is an [updated version of the Pug.js README.md](https://github.com/PythonLinks/pug/blob/master/README.md#installation-on-the-client) which should answer your question. 

There are relatively few of us compiling Pug on the client, so I am curious what is your use case?

**Comment by hmouhtar** [comment] 2019-02-13 13:49
@PythonLinks I'm working with DOM manipulation/events so I have to create nodes dynamically based on pre-defined templates. I've thought of 2 ways of creating these templates with pug:

1 - I could create a JS file that exports a template literal, which can be easily done with plain HTML. However, in order to do this, I guess that I would have to play around with pug to compile the .pug files into .js files with the ES6 export markup already included so the result can be imported directly by javascript.

2 - I could just directly compile it at the browser on real-time (which is what I'm currently trying to do.)

I'm by no means an expert and there is probably a better way to do it, so if you can think of any or have any recommendation, I'd love to know it.

**Comment by PythonLinks** [comment] 2019-02-13 17:04
@hmoutjar

Thank you for describing your problem. 

Flame shield Up.  Incoming controversial opinions.  

> I'm by no means an expert and there is probably a better way to do it, so if you can think of any or have any > recommendation, I'd love to know it.

I am also not an expert. But I do have the best Pug demo on the web!  ;-) 
 I think software should be made easier to use.   
  I could never figure out how to make that exports stuff work. I would have had to learn yet another tool.  And then maybe it would not work  
In fact one tool did not work.  So I took a different approach. 


What I increasingly find is that the software stack is targeted at large companies.  They have all the money.   The whole export  thing makes a huge deal of sense if you have large numbers of developers and libraries that have to interoperate. 
But if you a one man shop, a full stack developer, you have so many tools to learn that you cannot figure them all out.  

So I had the same problem.  I could not get it all working together, so I stripped out six lines of export from the runtime, and everything works great.  

Okay, so what should you do?  First from my README.md pull request. 

> If you want to compile Pug templates in the browser you need to include Pug for the browser. Here is the  
> latest version of Pug for the browser in standalone form. It only supports the very latest browsers, though, > and is a large file, and compilation is comparatively slow, so it is recommended that only the developers do > this, and then save and serve the generated javascript.

So best not to compile on your end user's client.  They might be on a slow small cell phone.  You can compile on the command line.  Installing node scared me off.  In retrospect, it is probably not that hard to do, but I did not want to add another tool to my tool chain.  So the simple solution is to go to my demo, and compile it there, and just save the javascript.  

Pretty soon my [JSON Wiki](https://pythonlinks.info/json-wiki) will be available as a docker container, and then you can just add it into your web server.  In the meantime copy and paste works pretty well. 

You have a number of compile options.  Check out the new buttons on the bottom of my demo page. 
The simple way is to include the runtime  in the function during compilation.  The better way is to not include the runtime, but load it separately.  The problem is that the exports stuff does not run in the browser.  You could figure out how to use a bundler, but that is yet another tool to learn.     If you go to my demo site, it includes a runtime with the Exports removed.   You are welcome to use it. 
I do not post it here, because it violates philosophy of the large team developers.   No point upsetting people. 

lozinski@PythonLinks.info if you want me to find it and send it to you. 

Flame shield down.

**Comment by ForbesLindesay** [comment] 2019-02-13 18:13
Duplicate of #3094

**Closed by ForbesLindesay** 2019-02-13 18:13 UTC
Labels: documentation

**Comment by hmouhtar** [comment] 2019-02-14 13:29
@PythonLinks Thanks for the awesome explanation! Really appreciate that you took the time to explain it better to me. I would like to show you an example of my code. First, I'm currently using Webpack to bundle all my dependencies together.

Now, this is a function at my `main.js` file:

```
let generateTableRow = () => {
  return htmlToElement(`
    <tr>
      <th><input required type="text" placeholder="Project's name"></th>
      <th><input required type="number" placeholder="ID Number"></th>
      <th><input required type="email" placeholder="Client's Email"></th>
    </tr>
  `);
}
```

So, something that would really make things visually easier would be to use pug instead of HTML on the JS side. Problem is, that would involve using pug on the browser which could severely affect performance. 

I'm thinking that a possible solution would be some sort of webpack plugin that converts pug code into HTML at the compilation time. Similar to what already happens with ES6 when it gets converted to ES5.

Do you know about any possible workaround? I don't know if there is already something like this developed for webpack.

**Comment by ForbesLindesay** [comment] 2019-02-14 16:51
@hmouhtar You might want to take a look at https://github.com/pugjs/babel-plugin-transform-react-pug - it's for react rather than pure DOM, but you could build a pure DOM version of it, with a bit of work.

**Comment by PythonLinks** [comment] 2019-02-14 17:20
There is a pug compile option which compiles PUG directly to  HTML. 

If you liked what I wrote, cuold you be so kind as to upvote my pull request. 

[README.md Improvements](https://github.com/pugjs/pug/pull/3096)

Any other upvotes would also be most appreciated.  The better the home page is the more 
people will invest in improving Pug.js.
