### ISSUE TITLE
include problem with version 2.0

### ISSUE THREAD

**Issue by ozluy** [pugjs/pug#2344] opened 2016-04-30 16:20 UTC
I use now version 2.0 and I did not have this issue with version 1.3.0 but  now **include** jade file creates **text** instead of **code block** of pug

### index.pug
```jade
doctype html
html
  head
    title  Yusuf Özlü (ozluy)
    meta(name='viewport' content ='width=device-width, initial-scale=1, user-scalable=no')
    meta(charset='utf-8')
    meta(http-equiv='X-UA-Compatible', content ='IE=edge')
    link(href='styles/bundle.css', rel='stylesheet', type='text/css')
    link(rel='shortcut-icon', href='favicon.ico')
  body
    include partials/_footer.jade
    script(src='scripts/bundle.js' )
```

### footer.jade
```
footer
  p hello I am footer
```

### html

```html

<!DOCTYPE html>
<html>
  <head>
    <title> Yusuf Özlü (ozluy)</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="styles/bundle.css" rel="stylesheet" type="text/css">
    <link rel="shortcut-icon" href="favicon.ico">
  </head>
  <body>  footer
    p hello I am footer

    <script src="scripts/bundle.js"></script>
  </body>
</html>
```

**Comment by DFOXpro** [comment] 2016-05-01 23:04
renaming the .jade files to pg solve this issue, btw the team will deprecate all the jade file extension in 2.0 release?

**Comment by ozluy** [comment] 2016-05-02 06:12
including .pug files gives me error with **gulp-pug** and **gulp-jade**
but this issue gone once I switch from **gulp-pug** to **gulp-jade**
Cheers!

**Comment by ForbesLindesay** [comment] 2016-05-14 11:04
Duplicate of #2299

**Closed by ForbesLindesay** 2016-05-14 11:04 UTC
